In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("./map_data.csv")

In [4]:
df

,ID (Station ID),Station Names,Dist. From First Station(km),Metro Line,Latitude,Longitude
0,1,Shaheed Sthal,0.0,Red line,28.670611,77.415582
1,2,Hindon River,1.0,Red line,28.673400,77.406400
2,3,Arthala,2.5,Red line,28.676999,77.391892
3,4,Mohan Nagar,3.2,Red line,28.672800,77.386300
4,5,Shyam park,4.5,Red line,28.676700,77.371200
...,...,...,...,...,...,...
269,2,Shivaji Stadium,1.9,Orange line,28.629010,77.211900
270,3,Dhaula Kuan,8.3,Orange line,28.591780,77.161550
271,4,Delhi Aerocity,14.5,Orange line,28.548810,77.120920
272,5,IGI Airport,17.9,Orange line,28.556930,77.086690
273,6,Dwarka Sector 21,20.8,Orange line,28.552260,77.058280

In [7]:
df["Station Names"].unique()

array(['Shaheed Sthal', 'Hindon River', 'Arthala', 'Mohan Nagar',
       'Shyam park', 'Major Mohit Sharma', 'Raj Bagh', 'Shaheed Nagar',
       'Dilshad Garden', 'Jhil Mil', 'Mansarovar Park', 'Shahdara',
       'Welcome', 'Seelampur', 'Shastri Park', 'Kashmere Gate',
       'Tis Hazari', 'Pul Bangash', 'Pratap Nagar', 'Shastri Nagar',
       'Inderlok', 'Kanhaiya Nagar', 'Keshav Puram',
       'Netaji Subash Place', 'Kohat Enclave', 'Pitam Pura',
       'Rohini East', 'Rohini West', 'Rithala', 'Samaypur Badli',
       'Rohini Sector 18-19', 'Haiderpur Badli Mor', 'Jahangirpuri',
       'Adarsh Nagar', 'Azadpur', 'Model Town', 'Guru Tegh Bahadur Nagar',
       'Vishwavidyalaya', 'Vidhan Sabha', 'Civil Lines', 'Chandni Chowk',
       'Chawri Bazar', 'New Delhi', 'Rajiv Chowk', 'Patel Chowk',
       'Central Secretariat', 'Udyog Bhawan', 'Lok Kalyan Marg',
       'Jor Bagh', 'Dilli Haat INA', 'AIIMS', 'Green Park', 'Hauz Khas',
       'Malviya Nagar', 'Saket', 'Qutab Minar', 'Chhattarpur',
       'Sultanpur', 'Ghitorni', 'Arjan Garh', 'Guru Dronacharya',
       'Sikandarpur', 'MG Road', 'IFFCO Chowk', 'Huda City Centre',
       'Dwarka Sector 21', 'Dwarka Sector 8', 'Dwarka Sector 9',
       'Dwarka Sector 10', 'Dwarka Sector 11', 'Dwarka Sector 12',
       'Dwarka Sector 13', 'Dwarka Sector 14', 'Dwarka', 'Dwarka Mor',
       'Nawada', 'Uttam Nagar West', 'Uttam Nagar East',
       'Janak Puri West', 'Janak Puri East', 'Tilak Nagar',
       'Subhash Nagar', 'Tagore Garden', 'Rajouri Garden', 'Ramesh Nagar',
       'Moti Nagar', 'Kirti Nagar', 'Shadipur', 'Patel Nagar',
       'Rajendra Place', 'Karol Bagh', 'Jhandewalan', 'R K Ashram Marg',
       'Barakhamba', 'Mandi House', 'Supreme Court (Pragati Maidan)',
       'Indraprastha', 'Yamuna Bank', 'Akshardham', 'Mayur Vihar Phase-1',
       'Mayur Vihar Extention', 'New Ashok Nagar', 'Noida Sector 15',
       'Noida Sector 16', 'Noida Sector 18', 'Botanical Garden',
       'Golf Course', 'Noida City Center', 'Noida Sector 34',
       'Noida Sector 52', 'Noida Sector 61', 'Noida Sector 59',
       'Noida Sector 62', 'Laxmi Nagar', 'Nirman Vihar', 'Preet Vihar',
       'Karkar Duma', 'Anand Vihar', 'Kaushambi', 'Vaishali',
       'Ashok Park Main', 'Satguru Ram Singh Marg', 'Punjabi Bagh',
       'Shivaji Park', 'Madipur', 'Paschim Vihar (East)',
       'Paschim Vihar (West)', 'Peera Garhi', 'Udyog Nagar',
       'Maharaja Surajmal Stadium', 'Nangloi', 'Nangloi Railway Station',
       'Rajdhani Park', 'Mundka', 'Mundka Industrial Area (MIA)',
       'Ghevra Metro station', 'Tikri Kalan', 'Tikri Border',
       'Pandit Shree Ram Sharma', 'Bahdurgarh City',
       'Brigadier Hoshiar Singh', 'Lal Quila', 'Jama Masjid',
       'Delhi Gate', 'ITO', 'Janpath', 'Khan Market',
       'Jawaharlal Nehru Stadium', 'Jangpura', 'Lajpat Nagar',
       'Moolchand', 'Kailash Colony', 'Nehru Place', 'Kalkaji Mandir',
       'Govind Puri', 'Okhla', 'Jasola', 'Sarita Vihar', 'Mohan Estate',
       'Tughlakabad', 'Badarpur Border', 'Sarai', 'N.H.P.C. Chowk',
       'Mewala Maharajpur', 'Sector 28 Faridabad', 'Badkal Mor',
       'Old Faridabad', 'Neelam Chowk Ajronda', 'Bata Chowk',
       'Escorts Mujesar', 'Sant Surdas - Sihi', 'Raja Nahar Singh',
       'Dabri Mor - Janakpuri South', 'Dashrath Puri', 'Palam',
       'Sadar Bazaar Cantonment', 'Terminal 1 IGI Airport',
       'Shankar Vihar', 'Vasant Vihar', 'Munirka', 'RK Puram',
       'IIT Delhi', 'Panchsheel Park', 'Chirag Delhi', 'Greater Kailash',
       'Nehru Enclave', 'Okhla NSIC', 'Sukhdev Vihar',
       'JAMIA MILLIA ISLAMIA', 'Okhla Vihar', 'Jasola Vihar Shaheen Bagh',
       'Kalindi Kunj', 'Okhla Bird Sanctuary', 'Majlis Park',
       'Shalimar Bagh', 'Shakurpur', 'Punjabi Bagh West',
       'ESI BASAI DARAPUR', 'Maya Puri', 'Naraina Vihar', 'Delhi Cantt',
       'Durgabai Deshmukh South Campus', 'Sir Vishweshwaraiah Moti Bagh',
       'Bhikaji Cama Place', 'Sarojini Nagar', 'South Extension',
       'Vinobapuri', 'Ashram', 'Sarai Kale Khan Hazrat Nizamuddin',
       'Mayur Vihar Pocket I', 'Trilokpuri Sanjay Lake',
       'Vinod Nagar East', 'Mandawali - West Vinod Nagar', 'IP Extension',
       'Karkarduma Court', 'Krishna Nagar', 'East Azad Nagar',
       'Jaffrabad', 'Maujpur', 'Gokulpuri', 'Johri Enclave', 'Shiv Vihar',
       'Noida Sector 51', 'Noida Sector 50', 'Noida Sector 76',
       'Noida Sector 101', 'Noida Sector 81', 'NSEZ Noida',
       'Noida Sector 83', 'Noida Sector 137', 'Noida Sector 142',
       'Noida Sector 143', 'Noida Sector 144', 'Noida Sector 145',
       'Noida Sector 146', 'Noida Sector 147', 'Noida Sector 148',
       'Knowledge Park II', 'Pari Chowk Greater Noida',
       'Alpha 1 Greater Noida', 'Delta 1 Greater Noida', 'GNIDA Office',
       'Depot Greater Noida', 'Nangli', 'Najafgarh',
       'New Delhi-Airport Express', 'Shivaji Stadium', 'Dhaula Kuan',
       'Delhi Aerocity', 'IGI Airport'], dtype=object)

In [26]:
new_df = pd.DataFrame({"Start":[],"End":[],"Dist":[]})

In [27]:
new_df

Empty DataFrame
Columns: [Start, End, Dist]
Index: []

In [28]:
type(df["ID (Station ID)"][0])

numpy.int64

In [29]:
for i in range(0,len(df)):
    if(df.iloc[i]["ID (Station ID)"]!=1):
        new_df.loc[len(new_df)] = {
            "Start":df.iloc[i-1]["Station Names"],
             "End":df.iloc[i]["Station Names"],
            "Dist":(df.iloc[i]["Dist. From First Station(km)"]-df.iloc[i-1]["Dist. From First Station(km)"])
            }

In [30]:
new_df

                         Start                 End  Dist
0                Shaheed Sthal        Hindon River   1.0
1                 Hindon River             Arthala   1.5
2                      Arthala         Mohan Nagar   0.7
3                  Mohan Nagar          Shyam park   1.3
4                   Shyam park  Major Mohit Sharma   1.2
..                         ...                 ...   ...
257  New Delhi-Airport Express     Shivaji Stadium   1.9
258            Shivaji Stadium         Dhaula Kuan   6.4
259                Dhaula Kuan      Delhi Aerocity   6.2
260             Delhi Aerocity         IGI Airport   3.4
261                IGI Airport    Dwarka Sector 21   2.9

[262 rows x 3 columns]

In [31]:
new_df.to_csv("links.csv")